### 创建数组
你可以使用array函数从常规的Python列表和元组创造数组。所创建的数组类型由原序列中的元素类型推导而来。

In [1]:
from numpy import *

In [2]:
a = array([2,3,4])
a

array([2, 3, 4])

In [3]:
a.dtype

dtype('int32')

In [4]:
b = array([1.2,3.5,5.2])
b.dtype

dtype('float64')

数组将序列包含序列转化成二维的数组，序列包含序列包含序列转化成三维数组等等。 

In [5]:
b = array([(1.5,2,3),(4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

数组类型可以在创建时显示指定 

In [6]:
c = array([[1,2],[3,4]],dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

通常，数组的元素开始都是未知的，但是它的大小已知。因此，NumPy提供了一些使用占位符创建数组的函数。这最小化了扩展数组的需要和高昂的运算代价。 
函数function创建一个全是0的数组，函数ones创建一个全1的数组，函数empty创建一个内容随机并且依赖与内存状态的数组。默认创建的数组类型(dtype)都是float64。 

In [7]:
zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
ones((2,3,4),dtype=int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [9]:
empty((2,3))

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

为了创建一个数列，NumPy提供一个类似arange的函数返回数组而不是列表: 

In [10]:
arange(10,30,5)

array([10, 15, 20, 25])