### 基本运算
数组的算术运算是按元素的。新的数组被创建并且被结果填充。 

In [4]:
from numpy import *
a = array([10,20,30,40])
a

array([10, 20, 30, 40])

In [6]:
b = arange(4)
b

array([0, 1, 2, 3])

In [7]:
c = a-b
c

array([10, 19, 28, 37])

In [9]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [10]:
10*sin(a)

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [11]:
a<35

array([ True,  True,  True, False], dtype=bool)

不像许多矩阵语言，NumPy中的乘法运算符*指示按元素计算，矩阵乘法可以使用dot函数或创建矩阵对象实现(参见教程中的矩阵章节) 

In [12]:
A = array([[1,1],[0,1]])
B = array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [13]:
dot(A,B)

array([[5, 4],
       [3, 4]])

有些操作符像+=和*=被用来更改已存在数组而不创建一个新的数组。 

In [15]:
a = ones((2,3),dtype=int)
b = random.random((2,3))
a *=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [16]:
b +=a
b

array([[ 3.56121433,  3.23083346,  3.75652154],
       [ 3.99673674,  3.17184149,  3.46664704]])

当运算的是不同类型的数组时，结果数组和更普遍和精确的已知(这种行为叫做upcast)。 

In [17]:
a = ones(3,dtype=int32)
b = linspace(0,pi,3)
b.dtype.name

'float64'

In [19]:
c = a + b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [21]:
c.dtype.name

'float64'

In [22]:
d = exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [23]:
d.dtype.name

'complex128'

In [26]:
a = arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [27]:
a.sum()

105

In [28]:
a.min()

0

In [29]:
a.max()

14

这些运算默认应用到数组好像它就是一个数字组成的列表，无关数组的形状。然而，指定axis参数你可以吧运算应用到数组指定的轴上： 

In [33]:
b = arange(12).reshape(3,4)
b.ndim

2

In [35]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
b.sum(axis=1)

array([ 6, 22, 38])

In [39]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

通用函数(ufunc) 
NumPy提供常见的数学函数如sin,cos和exp。在NumPy中，这些叫作“通用函数”(ufunc)。在NumPy里这些函数作用按数组的元素运算，产生一个数组作为输出。

In [40]:
B = arange(3)
B

array([0, 1, 2])

In [41]:
exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [42]:
sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [43]:
C = array([2.,-1.,4.])
add(B,C)

array([ 2.,  0.,  6.])

更多函数all, alltrue, any, apply along axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, conjugate, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sometrue, sort, std, sum, trace, transpose, var, vdot, vectorize, where 参见:NumPy示例 