### 当运算和处理数组时，它们的数据有时被拷贝到新的数组有时不是。这通常是新手的困惑之源。这有三种情况: 

#### 完全不拷贝 
简单的赋值不拷贝数组对象或它们的数据。 

In [9]:
from numpy import *
a = arange(12)
b = a
b is a

True

In [3]:
b.shape = 3,4
a.shape

(3, 4)

Python 传递不定对象作为参考4，所以函数调用不拷贝数组。

In [4]:
def f(x):
    print(id(x))   # id is a unique identifier of an object
id(a)

2128532850768

In [5]:
f(a)

2128532850768


#### 视图(view)和浅复制 

不同的数组对象分享同一个数据。视图方法创造一个新的数组对象指向同一数据。 

In [6]:
c = a.view()
c is a

False

In [7]:
c.base is a

True

In [8]:
c.flags.owndata

False

In [9]:
c.shape = 2,6  # a's shape doesn't change

In [10]:
a.shape

(3, 4)

In [11]:
c[0,4]=1234    # a's data changes
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [12]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

切片数组返回它的一个视图： 

In [13]:
 s = a[ : , 1:3]     # spaces added for clarity; could balso be written "s = a[:,1:3]"

In [14]:
 s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### 函数和方法(method)总览 

这是个NumPy函数和方法分类排列目录。这些名字链接到<a href="https://docs.scipy.org/doc/numpy/reference/routines.html">NumPy示例</a>,你可以看到这些函数起作用。

创建数组 

arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r , zeros, zeros_like 

转化 

astype, atleast 1d, atleast 2d, atleast 3d, mat 

操作 

array split, column stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack 

询问 

all, any, nonzero, where 

排序

argmax, argmin, argsort, max, min, ptp, searchsorted, sort 

运算 

choose, compress, cumprod, cumsum, inner, fill, imag, prod, put, putmask, real, sum 

基本统计 

cov, mean, std, var 

基本线性代数 

cross, dot, outer, svd, vdot 

### 进阶
#### 广播法则
广播法则能使通用函数有意义地处理不具有相同形状的输入。 

广播第一法则是，如果所有的输入数组维度不都相同，一个“1”将被重复地添加在维度较小的数组上直至所有的数组拥有一样的维度。 

广播第二法则确定长度为1的数组沿着特殊的方向表现地好像它有沿着那个方向最大形状的大小。对数组来说，沿着那个维度的数组元素的值理应相同。 

应用广播法则之后，所有数组的大小必须匹配。更多细节可以从这个<a href="https://docs.scipy.org/doc/">文档</a>找到。 

### 花哨的索引和索引技巧 
NumPy比普通Python序列提供更多的索引功能。除了索引整数和切片，正如我们之前看到的，数组可以被整数数组和布尔数组索引。 
### 通过数组索引

In [3]:
a = arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121], dtype=int32)

In [4]:
i = array([1,1,3,8,5])
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [7]:
j = array([[3,4],[9,7]]) # a bidimensional array of indices
j


array([[3, 4],
       [9, 7]])

In [8]:
a[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

当被索引数组a是多维的时，每一个唯一的索引数列指向a的第一维[^5]。以下示例通过将图片标签用调色版转换成色彩图像展示了这种行为。

In [9]:
palette = array( [ [0,0,0],                # black
                  [255,0,0],              # red
                  [0,255,0],              # green
                  [0,0,255],              # blue
                  [255,255,255] ] )       # white
palette.shape


(5, 3)

In [14]:
image = array([[0,1,2,0],[0,3,4,0]])
b = palette[image]
b

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [15]:
b.shape

(2, 4, 3)

我们也可以给出不不止一维的索引，每一维的索引数组必须有相同的形状。 

In [14]:
a = arange(12).reshape(3,4)
i = array([[0,1],[1,2]]) # indices for the first dim of a
j = array([[2,1],[3,3]])  # indices for the second dim
print(a[i,j])   # i and j must have equal shape

[[ 2  5]
 [ 7 11]]


In [21]:
i

array([[0, 1],
       [1, 2]])

In [22]:
a[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
a.ndim

In [17]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [19]:
a[1,2]

6

In [11]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [12]:
a[i,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [16]:
a[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [23]:
l = [i,j]
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [25]:
print(l)

[array([[0, 1],
       [1, 2]]), array([[2, 1],
       [3, 3]])]


In [31]:
time = linspace(20,145,5)
time

array([  20.  ,   51.25,   82.5 ,  113.75,  145.  ])

In [27]:
data = sin(arange(20)).reshape(5,4)

In [28]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [33]:
ind = data.argmax(axis = 0)
ind

array([2, 0, 3, 1], dtype=int64)

In [35]:
time[ind]

array([  82.5 ,   20.  ,  113.75,   51.25])

你也可以使用数组索引作为目标来赋值： 

In [36]:
a = arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:
a[[1,3,4]]= 0
a

array([0, 0, 2, 0, 0])

然而，当一个索引列表包含重复时，赋值被多次完成，保留最后的值： 

In [38]:
a = arange(5)
a[[0,0,2]] = [1,2,3]
a

array([2, 1, 3, 3, 4])

即使0在索引列表中出现两次，索引为0的元素仅仅增加一次。这是因为Python要求a+=1和a=a+1等同。 

### 通过布尔数组索引
当我们使用整数数组索引数组时，我们提供一个索引列表去选择。通过布尔数组索引的方法是不同的我们显式地选择数组中我们想要和不想要的元素。 

我们能想到的使用布尔数组的索引最自然方式就是使用和原数组一样形状的布尔数组。 

In [40]:
a = arange(12).reshape(3,4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [41]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a[b]  # 1d array with the selected elements

array([ 5,  6,  7,  8,  9, 10, 11])

这个属性在赋值时非常有用： 

In [43]:
a[b] = 0                                   # All elements of 'a' higher than 4 become 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

你可以参考<a href="https://docs.scipy.org/doc/numpy-dev/user/quickstart.html">曼德博集合示例</a>看看如何使用布尔索引来生成曼德博集合的图像。 

第二种通过布尔来索引的方法更近似于整数索引；对数组的每个维度我们给一个一维布尔数组来选择我们想要的切片。 

In [44]:
a = arange(12).reshape(3,4)
b1 = array([False,True,True])
b2 = array([True,False,True,False])
a[b1,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a[:,b2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [46]:
a[b1,b2]

array([ 4, 10])

注意一维数组的长度必须和你想要切片的维度或轴的长度一致，在之前的例子中，b1是一个秩为1长度为三的数组(a的行数)，b2(长度为4)与a的第二秩(列)相一致

### ix_()函数

ix_函数可以为了获得<a href="https://zh.wikipedia.org/wiki/%E5%A4%9A%E5%85%83%E7%BB%84">多元组</a>的结果而用来结合不同向量。例如，如果你想要用所有向量a、b和c元素组成的三元组来计算a+b*c：

In [47]:
a = array([2,3,4,5])
b = array([8,5,4])
c = array([5,4,6,8,3])

ax,bx,cx = ix_(a,b,c)
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [48]:
bx

array([[[8],
        [5],
        [4]]])

In [49]:
cx

array([[[5, 4, 6, 8, 3]]])

In [50]:
ax.shape,bx.shape,cx.shape

((4, 1, 1), (1, 3, 1), (1, 1, 5))

In [51]:
result = ax+bx*cx
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

你也可以实行如下简化： 

In [54]:
def ufunc_reduce(ufct, *vectors):
    vs = ix_(*vectors)
    r = ufct.identity
    for v in vs:
        r = ufct(r,v)
    return r

然后这样使用它： 

In [55]:
ufunc_reduce(add,a,b,c)

array([[[15, 14, 16, 18, 13],
        [12, 11, 13, 15, 10],
        [11, 10, 12, 14,  9]],

       [[16, 15, 17, 19, 14],
        [13, 12, 14, 16, 11],
        [12, 11, 13, 15, 10]],

       [[17, 16, 18, 20, 15],
        [14, 13, 15, 17, 12],
        [13, 12, 14, 16, 11]],

       [[18, 17, 19, 21, 16],
        [15, 14, 16, 18, 13],
        [14, 13, 15, 17, 12]]])