### 当运算和处理数组时，它们的数据有时被拷贝到新的数组有时不是。这通常是新手的困惑之源。这有三种情况: 

#### 完全不拷贝 
简单的赋值不拷贝数组对象或它们的数据。 

In [2]:
from numpy import *
a = arange(12)
b = a
b is a

True

In [3]:
b.shape = 3,4
a.shape

(3, 4)

Python 传递不定对象作为参考4，所以函数调用不拷贝数组。

In [4]:
def f(x):
    print(id(x))   # id is a unique identifier of an object
id(a)

2128532850768

In [5]:
f(a)

2128532850768


#### 视图(view)和浅复制 

不同的数组对象分享同一个数据。视图方法创造一个新的数组对象指向同一数据。 

In [6]:
c = a.view()
c is a

False

In [7]:
c.base is a

True

In [8]:
c.flags.owndata

False

In [9]:
c.shape = 2,6  # a's shape doesn't change

In [10]:
a.shape

(3, 4)

In [11]:
c[0,4]=1234    # a's data changes
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [12]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

切片数组返回它的一个视图： 

In [13]:
 s = a[ : , 1:3]     # spaces added for clarity; could balso be written "s = a[:,1:3]"

In [14]:
 s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### 函数和方法(method)总览 

这是个NumPy函数和方法分类排列目录。这些名字链接到<a href="https://docs.scipy.org/doc/numpy/reference/routines.html">NumPy示例</a>,你可以看到这些函数起作用。