### 更改数组的形状
一个数组的形状由它每个轴上的元素个数给出：

In [4]:
from numpy import *

a = floor(10*random.random([3,4]))
a

array([[ 3.,  1.,  3.,  4.],
       [ 2.,  1.,  6.,  2.],
       [ 7.,  0.,  6.,  7.]])

In [5]:
a.shape

(3, 4)

一个数组的形状可以被多种命令修改： 

In [6]:
a.ravel()

array([ 3.,  1.,  3.,  4.,  2.,  1.,  6.,  2.,  7.,  0.,  6.,  7.])

In [8]:
a.shape = (6,2)
a.transpose()

array([[ 3.,  3.,  2.,  6.,  7.,  6.],
       [ 1.,  4.,  1.,  2.,  0.,  7.]])

由ravel()展平的数组元素的顺序通常是“C风格”的，就是说，最右边的索引变化得最快，所以元素a[0,0]之后是a[0,1]。如果数组被改变形状(reshape)成其它形状，数组仍然是“C风格”的。NumPy通常创建一个以这个顺序保存数据的数组，所以ravel()将总是不需要复制它的参数3。但是如果数组是通过切片其它数组或有不同寻常的选项时，它可能需要被复制。函数reshape()和ravel()还可以被同过一些可选参数构建成FORTRAN风格的数组，即最左边的索引变化最快。

reshape函数改变参数形状并返回它，而resize函数改变数组自身。

In [9]:
a

array([[ 3.,  1.],
       [ 3.,  4.],
       [ 2.,  1.],
       [ 6.,  2.],
       [ 7.,  0.],
       [ 6.,  7.]])

In [11]:
a.resize(2,6)
a

array([[ 3.,  1.,  3.,  4.,  2.,  1.],
       [ 6.,  2.,  7.,  0.,  6.,  7.]])

如果在改变形状操作中一个维度被给做-1，其维度将自动被计算 
更多 shape, reshape, resize, ravel 参考NumPy示例 