### 当你打印一个数组，NumPy以类似嵌套列表的形式显示它，但是呈以下布局： 

#### 最后的轴从左到右打印 
#### 次后的轴从顶向下打印 
##### 剩下的轴从顶向下打印，每个切片通过一个空行与下一个隔开 

一维数组被打印成行，二维数组成矩阵，三维数组成矩阵列表。 

In [2]:
from numpy import *

In [3]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
b = arange(12).reshape(4,3)

In [6]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
c = arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


查看形状操作一节获得有关reshape的更多细节 
如果一个数组用来打印太大了，NumPy自动省略中间部分而只打印角落 

In [8]:
print(arange(1000000))

[     0      1      2 ..., 999997 999998 999999]


In [10]:
print(arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


禁用NumPy的这种行为并强制打印整个数组，你可以设置printoptions参数来更改打印选项。 

In [11]:
 set_printoptions(threshold='nan') 