### 用字符串索引 

参见RecordArray

### 简单数组运算
参考numpy文件夹中的linalg.py获得更多信息

In [1]:
from numpy import *
from numpy.linalg import *

a = array([[1.0, 2.0], [3.0, 4.0]])
a

array([[ 1.,  2.],
       [ 3.,  4.]])

In [2]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [3]:
inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
u = eye(2) # unit 2x2 matrix; "eye" represents "I"
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [6]:
j = array([[0.0, -1.0], [1.0, 0.0]])
dot(j,j)

array([[-1.,  0.],
       [ 0., -1.]])

In [7]:
j*j

array([[ 0.,  1.],
       [ 1.,  0.]])

In [8]:
trace(u)

2.0

In [10]:
y = array([[5.],[7.]])

In [11]:
solve(a,y)

array([[-3.],
       [ 4.]])