### 矩阵类 
这是一个关于矩阵类的简短介绍。

In [1]:
from numpy import *

A = matrix('1.0 2.0;3.0 4.0')

In [2]:
A

matrix([[ 1.,  2.],
        [ 3.,  4.]])

In [3]:
type(A)

numpy.matrixlib.defmatrix.matrix

In [4]:
A.T #transpose

matrix([[ 1.,  3.],
        [ 2.,  4.]])

In [5]:
X = matrix('5.0 7.0')
Y = X.T
Y

matrix([[ 5.],
        [ 7.]])

In [6]:
print(A*Y)

[[ 19.]
 [ 43.]]


In [7]:
dot(A,Y)

matrix([[ 19.],
        [ 43.]])

In [8]:
print(A.I)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
linalg.solve(A,Y)   # solving linear equation

matrix([[-3.],
        [ 4.]])

### 索引：比较矩阵和二维数组 
注意NumPy中数组和矩阵有些重要的区别。NumPy提供了两个基本的对象：一个N维数组对象和一个通用函数对象。其它对象都是建构在它们之上的。特别的，矩阵是继承自NumPy数组对象的二维数组对象。对数组和矩阵，索引都必须包含合适的一个或多个这些组合：整数标量、省略号(ellipses)、整数列表;布尔值，整数或布尔值构成的元组，和一个一维整数或布尔值数组。矩阵可以被用作矩阵的索引，但是通常需要数组、列表或者其它形式来完成这个任务。 

像平常在Python中一样，索引是从0开始的。传统上我们用矩形的行和列表示一个二维数组或矩阵，其中沿着0轴的方向被穿过的称作行，沿着1轴的方向被穿过的是列。

让我们创建数组和矩阵用来切片： 

In [12]:
A = arange(12)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
A.shape = (3,4)
M = asmatrix(A)
print(type(A),end="  ")
print(type(M))

<class 'numpy.ndarray'>  <class 'numpy.matrixlib.defmatrix.matrix'>


现在，让我们简单的切几片。基本的切片使用切片对象或整数。例如，A[:]和M[:]的求值将表现得和Python索引很相似。然而要注意很重要的一点就是NumPy切片数组不创建数据的副本;切片提供统一数据的视图。 

In [15]:
print(A[:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
print(A[:].shape)

(3, 4)


In [27]:
print(M[:]);print(M[:].shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [22]:
help(mat)

Help on function asmatrix in module numpy.matrixlib.defmatrix:

asmatrix(data, dtype=None)
    Interpret the input as a matrix.
    
    Unlike `matrix`, `asmatrix` does not make a copy if the input is already
    a matrix or an ndarray.  Equivalent to ``matrix(data, copy=False)``.
    
    Parameters
    ----------
    data : array_like
        Input data.
    dtype : data-type
       Data-type of the output matrix.
    
    Returns
    -------
    mat : matrix
        `data` interpreted as a matrix.
    
    Examples
    --------
    >>> x = np.array([[1, 2], [3, 4]])
    
    >>> m = np.asmatrix(x)
    
    >>> x[0,0] = 5
    
    >>> m
    matrix([[5, 2],
            [3, 4]])



In [28]:
print(A[:,1]);print(A[:,1].shape)

[1 5 9]
(3,)


In [30]:
print(M[:,1]);print(M[:,1].shape)

[[1]
 [5]
 [9]]
(3, 1)


注意最后两个结果的不同。对二维数组使用一个冒号产生一个一维数组，然而矩阵产生了一个二维矩阵。10例如，一个M[2,:]切片产生了一个形状为(1,4)的矩阵，相比之下，一个数组的切片总是产生一个最低可能维度11的数组。例如，如果C是一个三维数组，C[...,1]产生一个二维的数组而C[1,:,1]产生一个一维数组。从这时开始，如果相应的矩阵切片结果是相同的话，我们将只展示数组切片的结果。 

假如我们想要一个数组的第一列和第三列，一种方法是使用列表切片：

In [31]:
A[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

稍微复杂点的方法是使用take()方法(method): 

In [32]:
 A[:,].take([1,3],axis=1)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

如果我们想跳过第一行，我们可以这样： 

In [33]:
A[1:,].take([1,3],axis=1)

array([[ 5,  7],
       [ 9, 11]])

或者我们仅仅使用A[1:,[1,3]]。还有一种方法是通过矩阵向量积(叉积)。 

In [35]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
 A[ix_((1,2),(1,3))]

array([[ 5,  7],
       [ 9, 11]])

现在让我们做些更复杂的。比如说我们想要保留第一行大于1的列。一种方法是创建布尔索引： 

In [37]:
A[0,:]>1

array([False, False,  True,  True], dtype=bool)

In [38]:
 A[:,A[0,:]>1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

就是我们想要的！但是索引矩阵没这么方便。 

In [40]:
M[0,:]>1

matrix([[False, False,  True,  True]], dtype=bool)

In [42]:
M

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

这个过程的问题是用“矩阵切片”来切片产生一个矩阵^12，但是矩阵有个方便的A属性，它的值是数组呈现的。所以我们仅仅做以下替代：

In [45]:
M[:,M.A[0,:]>1]

matrix([[ 2,  3],
        [ 6,  7],
        [10, 11]])