一维数组可以被索引、切片和迭代，就像列表和其它Python序列。 

In [10]:
from numpy import *
a = arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [11]:
a[2]

8

In [14]:
a[:6:2] = -1000 #从起始位到6的位置，步长为2的位置的元素设置为-1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729], dtype=int32)

In [6]:
a[: :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000], dtype=int32)

In [8]:
for i in a:
    print(i**(1/3.),end=" ")

nan 1.0 nan 3.0 nan 5.0 6.0 7.0 8.0 9.0 

C:\Users\admin\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


多维数组可以每个轴有一个索引。这些索引由一个逗号分割的元组给出。

In [16]:
def f(x,y):
    return 10*x + y
b = fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [17]:
b[2,3]

23

In [18]:
b[0:5,1]  # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [19]:
b[:,1] ## equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [20]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

当少于轴数的索引被提供时，确失的索引被认为是整个切片： 

In [22]:
b[-1]  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

### b[i]中括号中的表达式被当作i和一系列:，来代表剩下的轴。NumPy也允许你使用“点”像b[i,...]。 
### 点(…)代表许多产生一个完整的索引元组必要的分号。如果x是秩为5的数组(即它有5个轴)，那么: 
#### x[1,2,…] 等同于 x[1,2,:,:,:], 
#### x[…,3] 等同于 x[:,:,:,:,3] 
#### x[4,…,5,:] 等同 x[4,:,:,5,:]. 