### 组合(stack)不同的数组
几种方法可以沿不同轴将数组堆叠在一起： 

In [1]:
from numpy import *
a = floor(10*random.random([2,2]))
a

array([[ 1.,  2.],
       [ 8.,  7.]])

In [2]:
b = floor(10*random.random([2,2]))
b

array([[ 2.,  9.],
       [ 3.,  5.]])

In [4]:
vstack((a,b))

array([[ 1.,  2.],
       [ 8.,  7.],
       [ 2.,  9.],
       [ 3.,  5.]])

函数column_stack以列将一维数组合成二维数组，它等同与vstack对一维数组。 

In [5]:
column_stack((a,b)) #with 2D array

array([[ 1.,  2.,  2.,  9.],
       [ 8.,  7.,  3.,  5.]])

In [7]:
a = array([4.,2.])
b = array([2.,8.])

In [8]:
a[:,newaxis]  This allows to have a 2D columns vector

array([[ 4.],
       [ 2.]])

In [9]:
column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [10]:
vstack((a[:,newaxis],b[:,newaxis])) # The behavior of vstack is different

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

#### row_stack函数，另一方面，将一维数组以行组合成二维数组。 
#### 对那些维度比二维更高的数组，hstack沿着第二个轴组合，vstack沿着第一个轴组合,concatenate允许可选参数给出组合时沿着的轴。 
#### Note 
#### 在复杂情况下，r_[]和c_[]对创建沿着一个方向组合的数很有用，它们允许范围符号(“:”): 

In [11]:
r_[1:4,0,4]

array([1, 2, 3, 0, 4])

当使用数组作为参数时，r_和c_的默认行为和vstack和hstack很像，但是允许可选的参数给出组合所沿着的轴的代号。 
更多函数hstack , vstack, column_stack , row_stack , concatenate , c_ , r_ 参见NumPy示例. 

#### 将一个数组分割(split)成几个小数组
使用hsplit你能将数组沿着它的水平轴分割，或者指定返回相同形状数组的个数，或者指定在哪些列后发生分割: 

In [13]:
 a = floor(10*random.random((2,12)))
a

array([[ 4.,  0.,  1.,  4.,  5.,  6.,  0.,  2.,  4.,  1.,  8.,  1.],
       [ 0.,  5.,  9.,  8.,  3.,  1.,  6.,  7.,  6.,  5.,  3.,  8.]])

In [14]:
hsplit(a,3)

[array([[ 4.,  0.,  1.,  4.],
        [ 0.,  5.,  9.,  8.]]), array([[ 5.,  6.,  0.,  2.],
        [ 3.,  1.,  6.,  7.]]), array([[ 4.,  1.,  8.,  1.],
        [ 6.,  5.,  3.,  8.]])]

In [15]:
 hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[ 4.,  0.,  1.],
        [ 0.,  5.,  9.]]), array([[ 4.],
        [ 8.]]), array([[ 5.,  6.,  0.,  2.,  4.,  1.,  8.,  1.],
        [ 3.,  1.,  6.,  7.,  6.,  5.,  3.,  8.]])]

vsplit沿着纵向的轴分割，array split允许指定沿哪个轴分割。 